repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      # Linter
      - id: ruff
        args: [--fix]
      # Formatter
      - id: ruff-format
  - repo: https://github.com/Yelp/detect-secrets
    rev: "v1.4.0"
    hooks:
      - id: detect-secrets
  - repo: https://github.com/pdm-project/pdm
    rev: 2.12.4
    hooks:
      - id: pdm-lock-check
