name: Test and publish release

on:
  push:
  pull_request:
  release:
    types: [published]

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.py }}
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
      - name: Print python version
        run: |
          python --version
          ${{ steps.setup-python.outputs.python-path }} --version
      #   - name: Install tox
      #     run: |
      #       pip install tox tox-pdm
      - name: Run pdm script
        run: |
          pdm use --python ${{ steps.setup-python.outputs.python-path }}
          pdm run all

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release' && github.event.action == 'published' && success()

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
      - name: Build package
        run: pdm build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
